name: Multi Environment Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Stage
        run: echo "Test stage completed"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build Stage
        run: echo "Build completed"

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: Print Dev Variable
        run: echo "${{vars.ENVIRONMENT}}"
      - name: Print url
        run: echo "${{vars.URL}}"

      - name: Deploy Dev
        run: echo "Deploying to Dev"


  deploy-sit:
    runs-on: ubuntu-latest
    environment: sit
    needs: deploy-dev
    steps:
      - name: Print SIT Variable
        run: echo "${{vars.ENVIRONMENT}}"
      - name: Print url
        run: echo "${{vars.URL}}"
      - name: Deploy SIT
        run: echo "Deploying to SIT"
